baseURL = "https://fascinating-chimera-fdec20.netlify.app/"
languageCode = "en-us"
title = "AdTuneAI"
theme = ["adtuneai-hugo-theme"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Features"
    url = "/features"
    weight = 2
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
